version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Building the application...
      - mvn clean package
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes